### ISSUE TITLE
IETF choices and opinions on market concentration / commercialization

### ISSUE THREAD

**Issue by nllz** [jariarkko/draft-iab-internet-consolidation#4]
Provide an overview of the existing decisions, documents, and opinions our community has made on this topic. Probably also good to go through earlier IAB statements. 

One could think of: RFC1192, and Clark, D. 1988. “The Design Philosophy of the DARPA Internet Protocols.” In Symposium Proceedings on Communications Architectures and Protocols, 106–114. SIGCOMM ’88. New York, NY, USA: ACM. https://doi.org/10.1145/52324.52336.

Maybe offset / introduce it via ways of RFC1958 and RFC3935.

**Comment by jariarkko** [comment]
This would be very useful.
