### ISSUE TITLE
Formulate an hypothesis or research questions, based on overviews and definition

### ISSUE THREAD

**Issue by nllz** [jariarkko/draft-iab-internet-consolidation#7]

**Comment by jariarkko** [comment]
Niels: 

I think formulating a hypothesis would fit a scientific article or work on this topic. But here, the intent is not to come up with new data or show correlation, but rather describe an issue. It would be useful though for the IAB to talk abut research questions that would be useful to answer by others? Is that what you meant?

**Comment by nllz** [comment]
Maybe we can solve this by restating:

How are technology
choices and fundamentals of communication affecting some of these trends?

into:

How is Internet consolidation influencing the development of the Internet infrastructure and architecture?

Maybe also clearly state this as the second question, since before that it is stated that:

Our first question is whether Internet is indeed consolidating?

**Comment by jariarkko** [comment]
Ok. Added some new material on this in b29400e.
